version: "3"

services:
  app:
    container_name: realtime
    build: ./
    working_dir: /var/www
    ports:
      - 8092:80
    volumes:
      - ./.docker/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/logs:/var/log/apache2
      - ./:/var/www
    networks:
      - localnet

networks:
  localnet:
    external: true
